name: Promote staging to production
on:
  push:
    tags:
      - '**'
  workflow_dispatch:
    inputs:
      quick_release:
        description: 'Quick release to production'
        type: boolean
        required: false
        default: false

jobs:
  promote-staging-to-production:
    uses: IMIO/gha-workflows/.github/workflows/promote-staging-to-production.yml@52677f55dd458fe3736fc999cfdaacfca5bf0049
    with:
      github_environment: production
      image_name: ${{ vars.IMAGE_NAME }}
      image_tag_staging: ${{ vars.IMAGE_TAG_STAGING }}
      image_tag_production: ${{ vars.IMAGE_TAG_PRODUCTION }}
      rundeck_job_id: ${{ vars.RUNDECK_JOB_ID }}
      node_name: ${{ vars.NODE_NAME }}
      runner_label: gha-runners-smartweb
      schedule_time: '03:00'
      service_name: ${{ vars.SERVICE_NAME }}
      quick_release: ${{ inputs.quick_release || false }}
    secrets:
      mattermost_webhook_url: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}
      registry_url: ${{ secrets.HARBOR_URL }}
      registry_username: ${{ secrets.SMARTWEB_HARBOR_USERNAME }}
      registry_password: ${{ secrets.SMARTWEB_HARBOR_PASSWORD }}
      rundeck_url: ${{ secrets.RUNDECK_URL }}
      rundeck_token: ${{ secrets.SMARTWEB_RUNDECK_TOKEN }}
