name: Promote staging to production
on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  promote-staging-to-production:
    uses: IMIO/gha-workflows/.github/workflows/promote-staging-to-production.yml@promote-staging-to-production
    with:
      github_environment: production
      image_name: ${{ vars.IMAGE_NAME }}
      image_tag_staging: ${{ vars.IMAGE_TAG_STAGING }}
      image_tag_production: 'testgha'
      rundeck_job_id: 5b7c2640-8494-4b52-b970-32745b326cd1
      node_name: 'centralizedsources001.staging.imio.be'
      runner_label: gha-runners-smartweb
      schedule_time: '03:00'
      service_name: ${{ vars.SERVICE_NAME }}
    secrets:
      mattermost_webhook_url: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}
      registry_url: ${{ secrets.HARBOR_URL }}
      registry_username: ${{ secrets.SMARTWEB_HARBOR_USERNAME }}
      registry_password: ${{ secrets.SMARTWEB_HARBOR_PASSWORD }}
      rundeck_url: ${{ secrets.RUNDECK_URL }}
      rundeck_token: ${{ secrets.SMARTWEB_RUNDECK_TOKEN }}
