name: Publish and deploy staging image
on:
  push:
    branches:
      - main
    tags:
      - '!**'
  workflow_dispatch:
jobs:
  build-push:
    environment: staging
    runs-on:
      group: self-hosted
    if: contains(github.event.head_commit.message, 'Back to development:') == false && contains(github.event.head_commit.message, 'Preparing release') == false
    steps:
      - name: Build push and notify
        uses: IMIO/gha/build-push-notify@v3.7.2
        with:
          IMAGE_NAME: ${{ vars.IMAGE_NAME }}
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/${{ vars.IMAGE_NAME }}:staging
            ${{ secrets.HARBOR_URL }}/${{ vars.IMAGE_NAME }}:staging-${{ github.run_number }}
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.SMARTWEB_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.SMARTWEB_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}
  deploy:
    environment:
      name: staging
    runs-on:
      group: self-hosted
    needs: build-push
    steps:
      - name: Deploy to staging and notify
        uses: IMIO/gha/rundeck-notify@v3.7.2
        with:
          RUNDECK_URL: ${{ secrets.RUNDECK_URL }}
          RUNDECK_TOKEN: ${{ secrets.SMARTWEB_RUNDECK_TOKEN }}
          RUNDECK_JOB_ID: ${{ vars.RUNDECK_JOB_ID }}
          RUNDECK_PARAMETERS: '-F "filter=name ${{ vars.NODE_NAME }}" -F "option.tag=${{ vars.IMAGE_TAG_STAGING }}" -F "option.image_name=${{ vars.IMAGE_NAME }}" -F "option.service_name=${{ vars.SERVICE_NAME }}"'
          MATTERMOST_WEBHOOK_URL: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}
